# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      runsOn: ubuntu-latest
      message: message from caller!!!
  # build:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [14.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm ci
  #   - run: npm run build --if-present
  #   - run: npm install jest
  #   - run: npm test
  deploy:
    # Add a dependency to the build job
    needs: call-workflow-build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
    #  - uses: ./.github/workflows/reusable-deploy.yml
     - run: echo "add code for deployment"
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: production-files
      #     path: ./dist
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.CI_CD_TOKEN }}
      #     publish_dir: ./dist
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable.yml
    # with:
    #     config-path: .github/caller.yml
    #     secrets: inherit