name: Reusable workflow build

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
      runsOn:
        required: true
        type: string
      message:
        required: true
        type: string
      jobName:
        required: false
        type: string
      jobType:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
    Job-steps:

        # runs-on: ubuntu-latest
        runs-on: ${{ inputs.runsOn }}
    
        strategy:
          matrix:
            node-version: [14.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - run: npm ci
        - run: npm run build --if-present
        - run: npm install jest
        - run: npm test
        - run: echo ${{ inputs.message }} 
          if: ${{ inputs.jobType == 'build'}}
        - run: echo "add steps specific to build stage"
        - run: echo " jobType ${{ inputs.jobType }}"

          if: ${{ inputs.jobType == 'deploy'}}
        - run: echo "Add steps specific to deploy stage"
        - run: echo " jobType ${{ inputs.jobType }}"
        